### ISSUE TITLE
Facing an error /var/projects/pyrlottie/pyrlottie/linux_aarch64/gif2webp: Exec format error\n'

### ISSUE THREAD

**Issue by DanielShum** [FHPythonUtils/PyRlottie#3]
Hi there, 

I am facing an error like this, just wondering if you can help?  Thanks you very much.

System: Ubuntu 18.04.5 LTS
Python version: 3.9

Traceback (most recent call last):
  File "/var/projects/pyrlottie/test.py", line 18, in <module>
    run(
  File "/var/projects/pyrlottie/pyrlottie/__init__.py", line 241, in run
    return asyncio.get_event_loop().run_until_complete(convMethod)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/projects/pyrlottie/pyrlottie/__init__.py", line 513, in convSingleLottie
    raise RuntimeError(f"{cmd=}: {ret=}")
RuntimeError: cmd='/var/projects/pyrlottie/pyrlottie/linux_aarch64/gif2webp /tmp/tmppgyk6g7f.gif -o out_convSingleLottie.webp -mt': ret=(2, b'/bin/sh: 1: /var/projects/pyrlottie/pyrlottie/linux_aarch64/gif2webp: Exec format error\n')

**Comment by FredHappyface** [comment]
Hey can you include a copy of the example code that caused this please? :)
